version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgres
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: postgresdb
      DB_POSTGRESDB_USER: root
      DB_POSTGRESDB_PASSWORD: root
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: chi@gmail.com
      N8N_BASIC_AUTH_PASSWORD: Admin12345
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      GENERIC_TIMEZONE: Asia/Jakarta
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data: